### ISSUE TITLE
 Edit http to https

### ISSUE THREAD

**Issue by juizmill** [adrianorsouza/reCAPTCHA-lib#1]
Edit the links that are at http to https to run on encrypted sites

**Comment by adrianorsouza** [comment]
I didn't quite understand your issue, but I supose you meant about enable HTTPS when loading the API, so for that you can enable via [Global Config](https://github.com/adrianorsouza/reCAPTCHA-lib#global-config) or [second parameter](https://github.com/adrianorsouza/reCAPTCHA-lib#run-recaptcha-over-ssl) in the constructor.
